version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "8080:8080"

  test:
    image: golang:latest
    container_name: test
    restart: always
    command: ["sh", "-c", "go mod tidy && go test ./... -v"]
    volumes:
      - .:/app
    working_dir: /app

  
